name: 'extranet-csh'

x-deploy: &deploy
  deploy:
    resources:
      limits:
        memory: 150M
        cpus: '0.01'

services:
  csh-backend:
    <<: *deploy
    build: backend-csh
    container_name: csh-backend
    restart: always
    env_file: './.env.secret'
    networks:
      - csh-back-net
      - csh-net

  csh-frontend:
    <<: *deploy
    build: frontend-csh
    container_name: csh-frontend
    restart: always
    ports:
      - "8000:8080"
    networks:
      - csh-net
    depends_on:
      - csh-backend

networks:
  csh-net:
  csh-back-net: