name: 'extranet-csh'

x-deploy: &deploy
  deploy:
    resources:
      limits:
        memory: 150M
        cpus: '0.01'

services:
  csh-backend:
    <<: *deploy
    build: backend-csh
    container_name: csh-backend
    restart: always
    env_file: './.env.secret'
    networks:
      - csh-back-net
      - csh-net

  csh-frontend:
    <<: *deploy
    build: frontend-csh
    container_name: csh-frontend
    restart: always
    environment:
      VITE_EXTRANET_CSH_PARISH_URL: https://www.paroissesaintroch.fr
      VITE_EXTRANET_CSH_INSTAGRAM_URL: https://www.instagram.com/cerclesainthonore/
      VITE_EXTRANET_CSH_YOUTUBE_URL: https://www.youtube.com/@cerclesthonore
      VITE_EXTRANET_CSH_FACEBOOK_URL: https://www.facebook.com/people/Cercle-Saint-Honoré/100089446511533/
      VITE_EXTRANET_CSH_API_URL: http://localhost:8080/api
      VITE_EXTRANET_CSH_SUPPORT_EMAIL: ravaux.noah@gmail.com
    networks:
      - csh-net
  
  nginx:
    <<: *deploy
    image: nginxinc/nginx-unprivileged:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      - csh-net
    ports:
      - "8000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - csh-backend
      - csh-frontend

networks:
  csh-net:
  csh-back-net: