name: 'extranet-csh'

services:
  csh-backend:
    build: backend-csh
    container_name: csh-backend
    restart: always
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: csh-backend
      MONGODB_PASSWORD: UNSECURE__CHANGE_THIS_PASSWORD
      MONGODB_DATABASE: CSH
      PORT: 3000
    networks:
      - csh-back-net
      - csh-net
    depends_on:
      - mongodb

  csh-frontend:
    build: frontend-csh
    container_name: csh-frontend
    restart: always
    environment:
      VITE_EXTRANET_PARISH_URL: https://www.paroissesaintroch.fr
      VITE_EXTRANET_INSTAGRAM_URL: https://www.instagram.com/cerclesainthonore/
      VITE_EXTRANET_YOUTUBE_URL=http: https://www.youtube.com/@cerclesthonore
      VITE_EXTRANET_API_URL: http://localhost:8080/api
    networks:
      - csh-net
  
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: csh-backend
      MONGO_INITDB_ROOT_PASSWORD: UNSECURE__CHANGE_THIS_PASSWORD
      MONGO_INITDB_DATABASE: CSH
    ports:
      - "27012:27017"
    networks:
      - csh-back-net
    volumes:
      - ./mongodb-data:/data/db
      - ./init_mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  nginx:
    image: nginxinc/nginx-unprivileged:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      - csh-net
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - csh-backend
      - csh-frontend

networks:
  csh-net:
  csh-back-net:

volumes:
  mongodb-data: