name: 'extranet-csh'

x-deploy: &deploy
  deploy:
    resources:
      limits:
        memory: 150M
        cpus: '0.01'

services:
  csh-backend:
    <<: *deploy
    build: backend-csh
    container_name: csh-backend
    restart: always
    env_file: './.env.secret'
    networks:
      - csh-back-net
      - csh-net

  csh-frontend:
    <<: *deploy
    build: frontend-csh
    container_name: csh-frontend
    restart: always
    networks:
      - csh-net
  
  nginx:
    <<: *deploy
    image: nginxinc/nginx-unprivileged:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      - csh-net
    ports:
      - "8000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - csh-backend
      - csh-frontend

networks:
  csh-net:
  csh-back-net: