name: 'extranet-csh'

services:
#  csh-backend:
#    build: csh-backend
#    container_name: csh-backend
#    restart: always
#    networks:
#      - csh-back-net
#      - csh-net
#    depends_on:
#      - mongodb

  csh-frontend:
    build: frontend-csh
    container_name: csh-frontend
    restart: always
    env_file:
      - frontend-csh/.env.production
    networks:
      - csh-net
  
#  mongodb:
#    image: mongo:7.0.5
#    container_name: mongodb
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: csh-backend
#      MONGO_INITDB_ROOT_PASSWORD: very_sercret_password
#      MONGO_INITDB_DATABASE: csh
#    networks:
#      - csh-back-net
#    volumes:
#      - mongodb-data:/data/db
#      - ./configs/init_mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  nginx:
    image: nginxinc/nginx-unprivileged:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      - csh-net
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
#      - csh-backend
      - csh-frontend

networks:
  csh-net:
#  csh-back-net:
#
#volumes:
#  mongodb-data: