name: 'extranet-csh'

x-deploy: &deploy
  deploy:
    resources:
      limits:
        memory: 300M
        cpus: '0.1'

services:
  csh-backend:
    <<: *deploy
    build: backend-csh
    container_name: csh-backend
    restart: always
    environment:
      MAIL_PASSWORD: ${CSH_MAIL_PASSWORD}
      JWT_SECRET_KEY: ${CSH_JWT_SECRET_KEY}
      FEEDBACK_EMAIL: noreply@cerclesainthonore.fr
      SUPPORT_EMAIL: cerclesthonore@gmail.com
      MONGODB_HOST: csh-mongodb
      MONGODB_DATABASE: CSH
      ORIGIN: https://cerclesainthonore.fr,https://www.cerclesainthonore.fr,https://admin.cerclesainthonore.fr,https://www.admin.cerclesainthonore.fr
      PORT: 3000
    networks:
      - csh-back-net
      - csh-net
    depends_on:
      - mongodb

  csh-frontend:
    <<: *deploy
    build: frontend-csh
    container_name: csh-frontend
    restart: always
    ports:
      - "8000:8080"
    networks:
      - csh-net
    depends_on:
      - csh-backend
    volumes:
      - /var/www/cerclesainthonore/assets/images/:/usr/share/nginx/html/assets/images/

  csh-admin:
    <<: *deploy
    build: admin-csh.old
    container_name: csh-admin
    restart: always
    ports:
      - "8002:8080"
    networks:
      - csh-net
    depends_on:
      - csh-backend
    volumes:
      - /var/www/cerclesainthonore/assets/images/:/usr/share/nginx/html/assets/images/

  mongodb:
    image: mongo:7.0.5
    container_name: csh-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: CSH
    networks:
      - csh-back-net
    volumes:
      - ./mongodb-data:/data/db
      - ./init_mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  csh-net:
  csh-back-net:

volumes:
  mongodb-data: