name: Deploy to Server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      env:
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        VPS_SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
      run: |
        ssh -o StrictHostKeyChecking=no csh@51.178.82.137 -p $VPS_SSH_PORT << EOF
          cd /home/csh/cerclesainthonore/extranet-csh
          git pull origin master
          touch .env.secret
          echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env.secret
          echo "MONGODB_PASSWORD=$DB_PASSWORD" >> .env.secret
          echo "MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD" >> .env.secret
          docker compose down --rmi all
          docker compose up -d
        EOF
