name: Deploy to Server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no csh@51.178.82.137 << 'EOF'
          cd /home/noah/cerclesainthonore/extranet-csh
          git pull origin master
          echo "MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}}" >> .env.secret
          docker compose down
          docker compose up -d
        EOF
